### ISSUE TITLE
provide badge for people to link to their projects

### ISSUE THREAD

**Issue by ry** [denoland/doc_website#65]
like doc.rs has

**Comment by lucacasonato** [comment]
I looked into this a week ago or so. Its really easy to add, I just didn't find a nice spot in the UI to put it.

Made some mockups with shields.io. What do you prefer? The Rust style with the version doesn't really work because we don't know anything about versions.

1. ![](https://img.shields.io/badge/denodoc-reference-5a77b2) (inspired by godoc)
2. ![](https://img.shields.io/badge/doc-reference-5a77b2?logo=deno) (logo in there?)
3. ![](https://img.shields.io/badge/docs-passing-success) (more like ci?)
4. ![](https://img.shields.io/badge/deno-doc-4D76AE) (docs.rs color scheme)

**Comment by ry** [comment]
4 seems good to me. What do you think?

**Comment by bartlomieju** [comment]
No 2 is very cute :)

**Comment by ry** [comment]
i think the logo in 2 is too low-res to be recognizable

**Comment by bartlomieju** [comment]
> i think the logo in 2 is too low-res to be recognizable

You're right, then no 4 seems good to me as well
